### ISSUE TITLE
[BUG]: hash() not working on SIMD vectors in 0.6.1

### ISSUE THREAD

**Issue by arthurevans** [modularml/mojo#1524]
### Bug description

Contrary to what it says in the changelog, `SIMD` does not implement `Hashable` in 0.6.1.

### Steps to reproduce

The following code fails on 0.6.1:

```
fn main():
    var s = SIMD[DType.float32, 4](7.1)
    var h = hash(s)
    print(h)
```

It produces the following error:

```
error: no matching function in call to 'hash': 
    var h = hash(s)
            ~~~~^~~
:1:1: note: candidate not viable: callee expects 1 input parameter, but 0 were specified
fn main():
^
:1:1: note: candidate not viable: callee expects 2 arguments, but 1 was specified
fn main():
^
mojo: error: failed to parse the provided Mojo
```

### System information

```shell
- macOS Ventura
- Mojo SDK v0.6.1
```

**Comment by arthurevans** [comment]
Summary: `Hashable` support landed in 0.6.1, but the trait wasn't not implemented on SIMD. So while you can't do `hash(simd)`, you can do this:

```
from builtin.hash import _hash_simd

fn main():
    var s = SIMD[DType.float32, 4](7.1)
    var h = _hash_simd(s)
    print(h)
```

In the next release, `SIMD` and a number of other built-in types should implement `Hashable`.
